name: 'data_signals'
version: '1.0.0'
config-version: 2

profile: 'data_signals'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  data_signals:
    staging:
      +materialized: view
    marts:
      +materialized: table
    signals:
      +materialized: table
